### ISSUE TITLE
[BUG] 3. Attempting to set Eventmie User model as parent to App\User  Unable to locate "app/User.php".

### ISSUE THREAD

**Issue by NagaprajwalB** [classiebit/eventmie#20]
3. Attempting to set Eventmie User model as parent to App\User

Unable to locate "app/User.php".  Did you move this file?
You will need to update this manually.  Change "extends Authenticatable" to "extends \Classiebit\Eventmie\Models\User" in your User model

---- Dumping the autoloaded files and reloading all new files ----

PHP Fatal error:  Declaration of Classiebit\Eventmie\Exceptions\MyHandler::report(Exception $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) in C:\xampp\htdocs\eventmie\vendor\classiebit\eventmie\src\Exceptions\MyHandler.php on line 36
PHP Fatal error:  Uncaught ReflectionException: Class "Classiebit\Eventmie\Exceptions\MyHandler" does not exist in C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php:944
Stack trace:
#0 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(944): ReflectionClass->__construct('Classiebit\\Even...')
#1 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(819): Illuminate\Container\Container->build('Classiebit\\Even...')
#2 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1048): Illuminate\Container\Container->resolve('Classiebit\\Even...', Array, false)
#3 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(324): Illuminate\Foundation\Application->resolve('Classiebit\\Even...', Array, false)
#4 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(937): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(819): Illuminate\Container\Container->build(Object(Closure))
#6 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1048): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#7 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(755): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#8 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1030): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#9 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(314): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#10 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(214): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#11 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#12 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(238): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#13 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(281): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#15 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [Classiebit\Eventmie\Exceptions\MyHandler] does not exist. in C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php:946
Stack trace:
#0 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(819): Illuminate\Container\Container->build('Classiebit\\Even...')
#1 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1048): Illuminate\Container\Container->resolve('Classiebit\\Even...', Array, false)
#2 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(324): Illuminate\Foundation\Application->resolve('Classiebit\\Even...', Array, false)
#3 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(937): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(819): Illuminate\Container\Container->build(Object(Closure))
#5 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1048): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#6 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php(755): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#7 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1030): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#8 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(314): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#9 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(214): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#11 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(238): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#12 C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(281): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#13 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#14 {main}
  thrown in C:\xampp\htdocs\eventmie\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 946

![image](https://github.com/user-attachments/assets/5f3722f1-86a3-4dd5-a5a6-7e17c124fbac)
 
 try solve this issue as soon as posible ...!!!!

**Comment by anuragdev2601** [comment]
hyy did you run this filee
